spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
       #native:
        #search-locations: "classpath:/config"
        #search-locations: "file:///C://Users//user//Downloads//config"
       git:
         uri: "https://github.com/LyamanNva/e-wallet-config.git"
         default-label: main
         timeout: 5
         clone-on-start: true
         force-pull: true
server:
  port: 8071

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
